export type AOType = "Travaux" | "Services" | "Fournitures";
export type AOSector = "Architecture" | "BTP" | "Urbanisme" | "Intérieur";
export type AOStatus = "Ouvert" | "Clôturé" | "Attribué";

export type AppelOffre = {
  id: string;
  title: string;
  organism: string;
  city: string;
  type: AOType;
  sector: AOSector;
  budget?: string;
  deadline: string;
  publishDate: string;
  source: string;
  sourceUrl: string;
  status: AOStatus;
  description: string;
  reference?: string;
};

export const APPELS_OFFRES: AppelOffre[] = [
  {
    id: "ao-001",
    title: "Études architecturales pour la construction d'un complexe sportif — Préparation Mondial 2030",
    organism: "Ministère de la Jeunesse et des Sports",
    city: "casablanca",
    type: "Services",
    sector: "Architecture",
    budget: "5 000 000 - 12 000 000 MAD",
    deadline: "2026-04-15",
    publishDate: "2026-03-20",
    source: "marchespublics.gov.ma",
    sourceUrl: "https://www.marchespublics.gov.ma/pmmp/",
    status: "Ouvert",
    description: "Mission complète de maîtrise d'œuvre pour la conception et le suivi de la construction d'un complexe sportif multidisciplinaire dans le cadre des infrastructures du Mondial 2030.",
    reference: "AO/MJS/2026-042",
  },
  {
    id: "ao-002",
    title: "Réhabilitation de 3 bâtiments administratifs — Commune de Rabat",
    organism: "Commune de Rabat",
    city: "rabat",
    type: "Travaux",
    sector: "Architecture",
    budget: "2 000 000 - 4 500 000 MAD",
    deadline: "2026-04-10",
    publishDate: "2026-03-15",
    source: "marchespublics.gov.ma",
    sourceUrl: "https://www.marchespublics.gov.ma/pmmp/",
    status: "Ouvert",
    description: "Travaux de réhabilitation incluant la mise aux normes parasismiques, l'accessibilité PMR et la rénovation énergétique de trois bâtiments administratifs.",
    reference: "AO/CR/2026-018",
  },
  {
    id: "ao-003",
    title: "Conception architecturale d'une médiathèque municipale",
    organism: "Commune de Marrakech",
    city: "marrakech",
    type: "Services",
    sector: "Architecture",
    budget: "800 000 - 1 500 000 MAD",
    deadline: "2026-04-20",
    publishDate: "2026-03-22",
    source: "marchespublics.gov.ma",
    sourceUrl: "https://www.marchespublics.gov.ma/pmmp/",
    status: "Ouvert",
    description: "Concours d'architecture pour la conception d'une médiathèque de 2 500 m² intégrant les matériaux locaux et l'architecture bioclimatique.",
    reference: "CONC/CM/2026-007",
  },
  {
    id: "ao-004",
    title: "Aménagement urbain du boulevard Mohammed VI — Phase 2",
    organism: "Agence Urbaine de Tanger",
    city: "tanger",
    type: "Services",
    sector: "Urbanisme",
    budget: "3 500 000 - 7 000 000 MAD",
    deadline: "2026-04-05",
    publishDate: "2026-03-10",
    source: "marchespublics.gov.ma",
    sourceUrl: "https://www.marchespublics.gov.ma/pmmp/",
    status: "Ouvert",
    description: "Études d'aménagement urbain et paysager du boulevard Mohammed VI incluant mobilier urbain, éclairage, espaces verts et voiries piétonnes.",
    reference: "AO/AUT/2026-033",
  },
  {
    id: "ao-005",
    title: "Construction de 120 logements sociaux — Programme INDH",
    organism: "Al Omrane Agadir",
    city: "agadir",
    type: "Travaux",
    sector: "BTP",
    budget: "15 000 000 - 25 000 000 MAD",
    deadline: "2026-03-30",
    publishDate: "2026-03-01",
    source: "marchespublics.gov.ma",
    sourceUrl: "https://www.marchespublics.gov.ma/pmmp/",
    status: "Clôturé",
    description: "Construction de 120 logements sociaux R+3 avec commerces en RDC dans le cadre du programme national INDH.",
    reference: "AO/AOA/2026-015",
  },
  {
    id: "ao-006",
    title: "Étude de faisabilité pour un éco-quartier à Zenata",
    organism: "Société d'Aménagement de Zenata (SAZ)",
    city: "casablanca",
    type: "Services",
    sector: "Urbanisme",
    budget: "1 200 000 - 2 500 000 MAD",
    deadline: "2026-04-25",
    publishDate: "2026-03-25",
    source: "marchespublics.gov.ma",
    sourceUrl: "https://www.marchespublics.gov.ma/pmmp/",
    status: "Ouvert",
    description: "Étude architecturale et urbanistique pour la conception d'un éco-quartier de 15 hectares intégrant des principes de développement durable et d'efficacité énergétique.",
    reference: "AO/SAZ/2026-009",
  },
  {
    id: "ao-007",
    title: "Rénovation de la Médina — Restauration de 5 fondouks historiques",
    organism: "Agence pour le Développement de Fès",
    city: "fes",
    type: "Travaux",
    sector: "Architecture",
    budget: "4 000 000 - 8 000 000 MAD",
    deadline: "2026-04-18",
    publishDate: "2026-03-18",
    source: "marchespublics.gov.ma",
    sourceUrl: "https://www.marchespublics.gov.ma/pmmp/",
    status: "Ouvert",
    description: "Restauration patrimoniale de 5 fondouks de la médina classée UNESCO. Architectes spécialisés en patrimoine requis.",
    reference: "AO/ADF/2026-022",
  },
  {
    id: "ao-008",
    title: "Aménagement intérieur des bureaux de l'ONCF — Gare de Kénitra",
    organism: "ONCF",
    city: "rabat",
    type: "Services",
    sector: "Intérieur",
    budget: "600 000 - 1 200 000 MAD",
    deadline: "2026-04-08",
    publishDate: "2026-03-12",
    source: "marchespublics.gov.ma",
    sourceUrl: "https://www.marchespublics.gov.ma/pmmp/",
    status: "Ouvert",
    description: "Conception et suivi d'aménagement intérieur des espaces administratifs et d'accueil de la nouvelle gare LGV de Kénitra.",
    reference: "AO/ONCF/2026-051",
  },
  {
    id: "ao-009",
    title: "Construction d'un centre hospitalier régional — CHR Meknès",
    organism: "Ministère de la Santé",
    city: "meknes",
    type: "Travaux",
    sector: "BTP",
    budget: "80 000 000 - 120 000 000 MAD",
    deadline: "2026-04-30",
    publishDate: "2026-03-28",
    source: "marchespublics.gov.ma",
    sourceUrl: "https://www.marchespublics.gov.ma/pmmp/",
    status: "Ouvert",
    description: "Construction d'un centre hospitalier régional de 250 lits incluant urgences, blocs opératoires, et héliport. Groupement architectes + BET requis.",
    reference: "AO/MS/2026-014",
  },
  {
    id: "ao-010",
    title: "Études architecturales — Extension du Terminal 2 de l'aéroport Mohammed V",
    organism: "ONDA",
    city: "casablanca",
    type: "Services",
    sector: "Architecture",
    budget: "8 000 000 - 15 000 000 MAD",
    deadline: "2026-05-15",
    publishDate: "2026-03-29",
    source: "marchespublics.gov.ma",
    sourceUrl: "https://www.marchespublics.gov.ma/pmmp/",
    status: "Ouvert",
    description: "Mission de maîtrise d'œuvre complète pour l'extension et la modernisation du Terminal 2. Capacité cible : 14 millions de passagers/an.",
    reference: "AO/ONDA/2026-003",
  },
  {
    id: "ao-011",
    title: "Conception d'un village artisanal touristique — Essaouira",
    organism: "Conseil Provincial d'Essaouira",
    city: "marrakech",
    type: "Services",
    sector: "Architecture",
    budget: "1 500 000 - 3 000 000 MAD",
    deadline: "2026-04-22",
    publishDate: "2026-03-19",
    source: "marocao.com",
    sourceUrl: "https://marocao.com/",
    status: "Ouvert",
    description: "Conception architecturale d'un village artisanal de 40 boutiques + espace d'exposition + restaurant, inspiration architecture traditionnelle Souiri.",
    reference: "AO/CPE/2026-011",
  },
  {
    id: "ao-012",
    title: "Maîtrise d'œuvre pour un campus universitaire — Université Euromed de Fès",
    organism: "Université Euromed de Fès",
    city: "fes",
    type: "Services",
    sector: "Architecture",
    budget: "6 000 000 - 10 000 000 MAD",
    deadline: "2026-04-28",
    publishDate: "2026-03-24",
    source: "marocao.com",
    sourceUrl: "https://marocao.com/",
    status: "Ouvert",
    description: "Conception d'un campus de 5 hectares incluant amphithéâtres, laboratoires, bibliothèque et résidence étudiante. Architecture contemporaine et durable exigée.",
    reference: "AO/UEMF/2026-002",
  },
  {
    id: "ao-013",
    title: "Aménagement paysager du Parc Hassan II — Casablanca",
    organism: "Casa Aménagement",
    city: "casablanca",
    type: "Services",
    sector: "Urbanisme",
    budget: "2 500 000 - 5 000 000 MAD",
    deadline: "2026-04-12",
    publishDate: "2026-03-14",
    source: "casa-amenagement.ma",
    sourceUrl: "https://www.casa-amenagement.ma/fr/appels-d-offres",
    status: "Ouvert",
    description: "Études paysagères et suivi de l'aménagement du Parc Hassan II. Intégration de jardins thématiques, plans d'eau et mobilier urbain.",
    reference: "AO/CA/2026-028",
  },
  {
    id: "ao-014",
    title: "Réhabilitation de riads en maisons d'hôtes — Programme touristique Marrakech",
    organism: "SMIT",
    city: "marrakech",
    type: "Travaux",
    sector: "Architecture",
    budget: "3 000 000 - 6 000 000 MAD",
    deadline: "2026-03-28",
    publishDate: "2026-02-25",
    source: "marocao.com",
    sourceUrl: "https://marocao.com/",
    status: "Clôturé",
    description: "Restauration et réhabilitation de 8 riads traditionnels en maisons d'hôtes de charme. Expertise en architecture patrimoniale marocaine requise.",
    reference: "AO/SMIT/2026-019",
  },
  {
    id: "ao-015",
    title: "Construction d'un centre commercial et de loisirs — Tanger City Center",
    organism: "Tanger Med Zones",
    city: "tanger",
    type: "Travaux",
    sector: "BTP",
    budget: "50 000 000 - 80 000 000 MAD",
    deadline: "2026-05-01",
    publishDate: "2026-03-27",
    source: "marchespublics.gov.ma",
    sourceUrl: "https://www.marchespublics.gov.ma/pmmp/",
    status: "Ouvert",
    description: "Construction d'un centre commercial et de loisirs de 35 000 m² sur 3 niveaux avec cinéma, food court, et parking souterrain 500 places.",
    reference: "AO/TMZ/2026-006",
  },
  {
    id: "ao-016",
    title: "Études techniques pour la mise à niveau des mosquées — Programme national",
    organism: "Ministère des Habous et des Affaires Islamiques",
    city: "rabat",
    type: "Services",
    sector: "Architecture",
    budget: "1 000 000 - 2 000 000 MAD",
    deadline: "2026-04-14",
    publishDate: "2026-03-16",
    source: "marchespublics.gov.ma",
    sourceUrl: "https://www.marchespublics.gov.ma/pmmp/",
    status: "Ouvert",
    description: "Études architecturales pour la restauration et la mise aux normes de 12 mosquées historiques. Connaissance du patrimoine islamique marocain requise.",
    reference: "AO/MHAI/2026-037",
  },
  {
    id: "ao-017",
    title: "Conception d'une station balnéaire éco-responsable — Plage de Sidi Ifni",
    organism: "Agence de Développement du Sud",
    city: "agadir",
    type: "Services",
    sector: "Architecture",
    budget: "2 000 000 - 4 000 000 MAD",
    deadline: "2026-05-10",
    publishDate: "2026-03-28",
    source: "marocao.com",
    sourceUrl: "https://marocao.com/",
    status: "Ouvert",
    description: "Concours d'architecture pour une station balnéaire éco-responsable. Bungalows, restaurant, spa et équipements nautiques. Empreinte carbone minimale exigée.",
    reference: "CONC/ADS/2026-004",
  },
  {
    id: "ao-018",
    title: "VRD et aménagement d'une zone industrielle — Meknès",
    organism: "Commune de Meknès",
    city: "meknes",
    type: "Travaux",
    sector: "BTP",
    budget: "10 000 000 - 18 000 000 MAD",
    deadline: "2026-04-16",
    publishDate: "2026-03-11",
    source: "marchespublics.gov.ma",
    sourceUrl: "https://www.marchespublics.gov.ma/pmmp/",
    status: "Ouvert",
    description: "Aménagement VRD d'une zone industrielle de 25 hectares : voiries, réseaux divers, éclairage public, espaces verts et signalétique.",
    reference: "AO/CMK/2026-041",
  },
];

export const AO_IDS = APPELS_OFFRES.map((ao) => ao.id);

export function getAppelOffreById(id: string) {
  return APPELS_OFFRES.find((ao) => ao.id === id);
}

export function getAppelsOffresByCity(city: string) {
  return APPELS_OFFRES.filter((ao) => ao.city === city);
}

export function getAppelsOffresByStatus(status: AOStatus) {
  return APPELS_OFFRES.filter((ao) => ao.status === status);
}

export function getOpenAppelsOffres() {
  return APPELS_OFFRES.filter((ao) => ao.status === "Ouvert").sort(
    (a, b) => new Date(a.deadline).getTime() - new Date(b.deadline).getTime()
  );
}
